name: Java CI Maven aarch64

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu binfmt-support qemu-user-static
          sudo apt-get install -y libc6:arm64
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build and Test in ARM64 container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace arm64v8/ubuntu:latest \
          /bin/bash -c "apt-get update && apt-get install -y openjdk-11-jdk maven && java -version && mvn -B package && java -jar target/headlong-cli-1.1-SNAPSHOT.jar -version"