name: Java CI gradle aarch64

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04 ]
        version: [ '22.0.2' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17 aarch64
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
          java-package: jdk
          architecture: aarch64
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          java -version
          chmod +x ./gradlew
          ./gradlew build fatJar --no-daemon
          java -jar build/libs/headlong-cli-1.1-SNAPSHOT.jar -version
