name: Java CI maven arm

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-22.04-arm, ubuntu-24.04-arm ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8 ARM
        uses: actions/setup-java@v4
        with:
          distribution: 'dragonwell'
          java-version: '8'
          java-package: jdk
          cache: 'maven'

      - name: Build with Maven
        run: |
          java -version
          mvn -B package --file pom.xml
          java -jar target/headlong-cli-1.2-SNAPSHOT.jar -version
