name: Java CI gradle

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ macos-13, macos-14, macos-15, ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 8 x64
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '8.0.202'
          java-package: jdk
          architecture: x64
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          java -version
          chmod +x ./gradlew
          ./gradlew build fatJar --no-daemon
          java -jar build/libs/headlong-cli-1.3-SNAPSHOT.jar -version
