name: Java CI gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 18.0.2
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '18.0.2'
          java-package: jdk
          architecture: x64

      - name: Build with Gradle
        run: gradle build
