name: Java CI gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8.0.422'
          java-package: jdk
          architecture: x86
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          java -version
          chmod +x ./gradlew
          ./gradlew build fatJar --no-daemon
          java -jar build/libs/headlong-cli-1.1-SNAPSHOT.jar -version
