name: Java CI gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 8.0.352
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8.0.352'
          java-package: jdk
          architecture: x86
          cache: 'gradle'

      - name: Build with Gradle
      - run:
          chmod +x ./gradlew
      - run:
          ./gradlew build --no-daemon
