name: Java CI gradle

on: [push]

jobs:
  build:

    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 1.8.0u345
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-openj9'
          java-version: '1.8.0u345'
          java-package: jdk
          architecture: x86

      - name: Build with Gradle
        run: gradle build
