name: Java CI gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 8.0.352
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8.0.352'
          java-package: jdk
          architecture: x86
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon
          java -jar build/libs/headlong-cli-1.1-SNAPSHOT.jar -version
