name: Java CI MacOS Gradle

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ macos-13, macos-14, macos-15 ]
        distribution: [ 'adopt-hotspot', 'adopt-openj9' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 16, x64
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: '16'
          java-package: jdk
          architecture: x64
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "7.6.4"

      - name: Build with Gradle
        run: |
          java -version
          gradle -version
          gradle build fatJar --no-daemon
          java -jar build/libs/headlong-cli-1.2-SNAPSHOT.jar -version