name: Java CI maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8.0
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '1.8.0'
          java-package: jdk
          architecture: armv7

      - name: Build with Maven
        run: mvn -B package --file pom.xml
