name: Java CI maven

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'dragonwell'
          java-version: '8'
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: |
          java -version
          mvn -B package --file pom.xml
          java -jar target/headlong-cli-1.3-SNAPSHOT.jar -version

