name: Java CI maven

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-24.04, windows-2019, windows-2022 ]
        version: [ '8' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8 x86
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018
        with:
          distribution: 'dragonwell'
          java-version: ${{ matrix.version }}
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: |
          java -version
          mvn -B package --file pom.xml
          java -jar target/headlong-cli-1.1-SNAPSHOT.jar -version

