name: Java CI maven

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 18.0.2
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '18.0.2'
          java-package: jdk
          architecture: x64

      - name: Build with Maven
        run: mvn -B package --file pom.xml
