name: Java CI maven

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ macos-12, macos-13, macos-14, ubuntu-22.04, windows-2019, windows-2022 ]
        version: [ '8', '22.0.2' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: |
          java -version
          mvn -B package --file pom.xml
          java -jar target/headlong-cli-1.1-SNAPSHOT.jar -version

