name: Java CI maven

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ macos-10.15, macos-12, ubuntu-18.04, windows-2019 ]
        version: [ '8', '19.0.1' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          java -jar target/headlong-cli-1.1-SNAPSHOT.jar -version

