name: Java CI maven

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18.0.1+10
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19.0.1'
          java-package: jdk
          architecture: x64

      - name: Build with Maven
        run: mvn -B package --file pom.xml
